export type Language = "en" | "hi";

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    billing: "Billing",
    inventory: "Inventory",
    customers: "Customers",
    expenses: "Expenses",
    insights: "Insights",
    settings: "Settings",
    suppliers: "Suppliers",
    reports: "Reports",

    // Billing
    newBill: "New Bill",
    invoice: "Invoice",
    invoiceNumber: "Invoice Number",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    total: "Total",
    amountPaid: "Amount Paid",
    balanceDue: "Balance Due",
    paymentMethod: "Payment Method",
    cash: "Cash",
    upi: "UPI",
    card: "Card",
    bankTransfer: "Bank Transfer",
    other: "Other",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    filter: "Filter",
    export: "Export",
    print: "Print",
    share: "Share",
    send: "Send",
    confirm: "Confirm",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    loading: "Loading...",

    // Inventory
    product: "Product",
    products: "Products",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    deleteProduct: "Delete Product",
    productName: "Product Name",
    sku: "SKU",
    price: "Price",
    cost: "Cost",
    stock: "Stock",
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    category: "Category",
    unit: "Unit",
    quantity: "Quantity",

    // Customers
    addCustomer: "Add Customer",
    editCustomer: "Edit Customer",
    customerName: "Customer Name",
    phone: "Phone",
    email: "Email",
    address: "Address",
    outstandingBalance: "Outstanding Balance",
    totalSpend: "Total Spend",
    purchaseCount: "Purchase Count",
    lastPurchase: "Last Purchase",

    // Expenses
    addExpense: "Add Expense",
    expenseDescription: "Expense Description",
    amount: "Amount",
    date: "Date",
    vendor: "Vendor",
    notes: "Notes",
    recurring: "Recurring",

    // Reports
    dailyReport: "Daily Report",
    weeklyReport: "Weekly Report",
    monthlyReport: "Monthly Report",
    salesReport: "Sales Report",
    profitLoss: "Profit & Loss",
    cashFlow: "Cash Flow",
    topProducts: "Top Products",
    topCustomers: "Top Customers",

    // General
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    thisMonth: "This Month",
    from: "From",
    to: "To",
    all: "All",
    active: "Active",
    inactive: "Inactive",
    status: "Status",
    createdAt: "Created At",
    updatedAt: "Updated At",
    actions: "Actions",
    noData: "No data found",
    confirmDelete: "Are you sure you want to delete?",
    success: "Success",
    error: "Error",
    language: "Language",
    english: "English",
    hindi: "हिन्दी",
  },
  hi: {
    // Navigation
    dashboard: "डैशबोर्ड",
    billing: "बिलिंग",
    inventory: "इन्वेंट्री",
    customers: "ग्राहक",
    expenses: "खर्च",
    insights: "अंतर्दृष्टि",
    settings: "सेटिंग्स",
    suppliers: "आपूर्तिकर्ता",
    reports: "रिपोर्ट",

    // Billing
    newBill: "नया बिल",
    invoice: "चालान",
    invoiceNumber: "चालान संख्या",
    subtotal: "उपयोग",
    discount: "छूट",
    tax: "कर",
    total: "कुल",
    amountPaid: "भुगतान राशि",
    balanceDue: "शेष राशि",
    paymentMethod: "भुगतान विधि",
    cash: "नकद",
    upi: "यूपीआई",
    card: "कार्ड",
    bankTransfer: "बैंक हस्तांतरण",
    other: "अन्य",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "जोड़ें",
    search: "खोजें",
    filter: "फ़िल्टर",
    export: "निर्यात",
    print: "प्रिंट",
    share: "शेयर",
    send: "भेजें",
    confirm: "पुष्टि करें",
    close: "बंद करें",
    back: "वापस",
    next: "अगला",
    previous: "पिछला",
    loading: "लोड हो रहा है...",

    // Inventory
    product: "उत्पाद",
    products: "उत्पाद",
    addProduct: "उत्पाद जोड़ें",
    editProduct: "उत्पाद संपादित करें",
    deleteProduct: "उत्पाद हटाएं",
    productName: "उत्पाद का नाम",
    sku: "एसकेयू",
    price: "मूल्य",
    cost: "लागत",
    stock: "स्टॉक",
    lowStock: "कम स्टॉक",
    outOfStock: "स्टॉक में नहीं",
    category: "श्रेणी",
    unit: "इकाई",
    quantity: "मात्रा",

    // Customers
    addCustomer: "ग्राहक जोड़ें",
    editCustomer: "ग्राहक संपादित करें",
    customerName: "ग्राहक का नाम",
    phone: "फ़ोन",
    email: "ईमेल",
    address: "पता",
    outstandingBalance: "शेष राशि",
    totalSpend: "कुल खर्च",
    purchaseCount: "खरीद गिनती",
    lastPurchase: "अंतिम खरीद",

    // Expenses
    addExpense: "खर्च जोड़ें",
    expenseDescription: "खर्च विवरण",
    amount: "राशि",
    date: "तारीख",
    vendor: "विक्रेता",
    notes: "नोट्स",
    recurring: "आवर्ती",

    // Reports
    dailyReport: "दैनिक रिपोर्ट",
    weeklyReport: "साप्ताहिक रिपोर्ट",
    monthlyReport: "मासिक रिपोर्ट",
    salesReport: "बिक्री रिपोर्ट",
    profitLoss: "लाभ और हानि",
    cashFlow: "नकदी प्रवाह",
    topProducts: "लोकप्रिय उत्पाद",
    topCustomers: "प्रमुख ग्राहक",

    // General
    today: "आज",
    yesterday: "कल",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    from: "से",
    to: "तक",
    all: "सभी",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    status: "स्थिति",
    createdAt: "बनाया गया",
    updatedAt: "अपडेट किया गया",
    actions: "कार्य",
    noData: "कोई डेटा नहीं मिला",
    confirmDelete: "क्या आप वाकई हटाना चाहते हैं?",
    success: "सफल",
    error: "त्रुटि",
    language: "भाषा",
    english: "English",
    hindi: "हिन्दी",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function t(key: TranslationKey, lang: Language = "en"): string {
  return translations[lang][key] || translations.en[key] || key;
}
