export type Language = "en";

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    billing: "Billing",
    inventory: "Inventory",
    customers: "Customers",
    expenses: "Expenses",
    insights: "Insights",
    settings: "Settings",
    suppliers: "Suppliers",
    reports: "Reports",

    // Billing
    newBill: "New Bill",
    invoice: "Invoice",
    invoiceNumber: "Invoice Number",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    total: "Total",
    amountPaid: "Amount Paid",
    balanceDue: "Balance Due",
    paymentMethod: "Payment Method",
    cash: "Cash",
    upi: "UPI",
    card: "Card",
    bankTransfer: "Bank Transfer",
    credit: "Credit",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    search: "Search",
    filter: "Filter",
    export: "Export",
    print: "Print",
    download: "Download",
    send: "Send",
    close: "Close",
    back: "Back",
    next: "Next",
    previous: "Previous",
    loading: "Loading...",
    noData: "No data available",
    confirm: "Confirm",
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Info",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    thisYear: "This Year",
    custom: "Custom",
    from: "From",
    to: "To",
    apply: "Apply",
    clear: "Clear",
    refresh: "Refresh",
    retry: "Retry",
    offline: "You're offline",
    syncing: "Syncing...",
    synced: "All changes synced",
    install: "Install",
    installed: "Installed",
  },
};

export function t(key: keyof typeof translations.en): string {
  return translations.en[key] || key;
}

export default translations;
